/*
 * OLA-HD Repository
 *
 * This is the API definition for the (OCR-D) OLA-HD Repository server. You can find out more about OLA-HD [http://ocr-d.de/modulprojekte#%20OLA-HD](http://ocr-d.de/modulprojekte#%20OLA-HD). For test purposes, you can use the api key `test-key` to test the authorization     filters.
 *
 * API version: 1.0.0
 * Contact: panzer@sub.uni-goettingen.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/lza/",
		Index,
	},

	Route{
		"AddBag",
		strings.ToUpper("Post"),
		"/lza/bag",
		AddBag,
	},

	Route{
		"DeleteBagById",
		strings.ToUpper("Delete"),
		"/lza/bag/{recordId}",
		DeleteBagById,
	},

	Route{
		"GetBagById",
		strings.ToUpper("Get"),
		"/lza/bag/{recordId}",
		GetBagById,
	},

	Route{
		"GetBagList",
		strings.ToUpper("Get"),
		"/lza/bag",
		GetBagList,
	},

	Route{
		"GetBagVersionById",
		strings.ToUpper("Get"),
		"/lza/bag/{recordId}/{versionId}",
		GetBagVersionById,
	},

	Route{
		"GetBagVersionsListById",
		strings.ToUpper("Get"),
		"/lza/bag/{recordId}/versions",
		GetBagVersionsListById,
	},

	Route{
		"UpdateBag",
		strings.ToUpper("Put"),
		"/lza/bag",
		UpdateBag,
	},

	Route{
		"GetFileByIds",
		strings.ToUpper("Get"),
		"/lza/content/{recordId}/{versionId}/{fileGrpUseId}/{fileId}",
		GetFileByIds,
	},

	Route{
		"GetFileListById",
		strings.ToUpper("Get"),
		"/lza/content/{recordId}/{versionId}",
		GetFileListById,
	},

	Route{
		"SearchBagsBySearchterm",
		strings.ToUpper("Get"),
		"/lza/search/{searchterm}",
		SearchBagsBySearchterm,
	},
}
